export const data = [
  { shlokaNumber: "1.1", shlokaText: "dharma-kṣetre kuru-kṣetre" },
  { shlokaNumber: "2.3", shlokaText: "klaibyaṁ mā sma gamaḥ pārtha" },
  { shlokaNumber: "2.12", shlokaText: "na tv evāhaṁ jātu nāsaṁ" },
  { shlokaNumber: "2.13", shlokaText: "dehino 'smin yatha dehe" },
  { shlokaNumber: "2.14", shlokaText: "matra- sparsa tu kaunteya" },
  { shlokaNumber: "2.22", shlokaText: "vāsāṁsi jīrṇāni yathā vihāya" },
  { shlokaNumber: "2.27", shlokaText: "jātasya hi dhruvo mṛtyur" },
  { shlokaNumber: "2.40", shlokaText: "nehābhikrama-nāśo ’sti" },
  { shlokaNumber: "2.41", shlokaText: "vyavasāyātmikā buddhir" },
  { shlokaNumber: "2.44", shlokaText: "bhogaiśvarya-prasaktānāṁ" },
  { shlokaNumber: "2.47", shlokaText: "karmany evadhikaras te" },
  { shlokaNumber: "2.62", shlokaText: "dhyāyato viṣayān puṁsaḥ" },
  { shlokaNumber: "2.63", shlokaText: "krodhād bhavati sammohaḥ" },
  { shlokaNumber: "2.71", shlokaText: "vihāya kāmān yaḥ sarvān" },
  { shlokaNumber: "3.8", shlokaText: "niyataṁ kuru karma tvaṁ" },
  { shlokaNumber: "3.13", shlokaText: "yajña-śiṣṭāśinaḥ santo" },
  { shlokaNumber: "3.20", shlokaText: "karmaṇaiva hi saṁsiddhim" },
  { shlokaNumber: "3.21", shlokaText: "yad yad acarti sresthas" },
  { shlokaNumber: "3.37", shlokaText: "kāma eṣha krodha eṣha" },
  { shlokaNumber: "3.39", shlokaText: "āvṛtaṁ jñānam etena" },
  { shlokaNumber: "4.7", shlokaText: "yada yada hi dharmasya" },
  { shlokaNumber: "4.8", shlokaText: "paritrāṇāya sādhūnāṁ" },
  { shlokaNumber: "4.9", shlokaText: "janma karma ca me divyam" },
  { shlokaNumber: "4.11", shlokaText: "ye yathā māṁ prapadyante" },
  { shlokaNumber: "4.20", shlokaText: "tyaktvā karma-phalāsaṅgaṁ" },
  { shlokaNumber: "5.2", shlokaText: "sannyāsaḥ karma-yogaś ca" },
  { shlokaNumber: "5.18", shlokaText: "vidyā-vinaya-sampanne" },
  { shlokaNumber: "5.22", shlokaText: "ye hi saṁsparśa-jā bhogā" },
  { shlokaNumber: "6.5", shlokaText: "uddhared ātmanātmānaṁ" },
  { shlokaNumber: "6.6", shlokaText: "bandhur ātmātmanas tasya" },
  { shlokaNumber: "6.17", shlokaText: "yuktahara-viharasya" },
  { shlokaNumber: "6.26", shlokaText: "yato yato niścalati" },
  { shlokaNumber: "6.30", shlokaText: "yo māṁ paśhyati sarvatra" },
  { shlokaNumber: "6.34", shlokaText: "cañcalaṁ hi manaḥ kṛṣṇa" },
  { shlokaNumber: "7.7", shlokaText: "mattaḥ parataraṁ nānyat" },
  { shlokaNumber: "7.8", shlokaText: "raso ’ham apsu kaunteya" },
  { shlokaNumber: "7.11", shlokaText: "balaṁ balavatāṁ cāhaṁ" },
  { shlokaNumber: "7.15", shlokaText: "na māṁ duṣkṛtino mūḍhāḥ" },
  { shlokaNumber: "7.16", shlokaText: "catur-vidhā bhajante māṁ" },
  { shlokaNumber: "7.21", shlokaText: "yo yo yāṁ yāṁ tanuṁ bhaktaḥ" },
  { shlokaNumber: "7.24", shlokaText: "avyaktaṁ vyaktim āpannaṁ" },
  { shlokaNumber: "7.25", shlokaText: "nāhaṁ prakāśaḥ sarvasya" },
  { shlokaNumber: "7.26", shlokaText: "vedāhaṁ samatītāni" },
  { shlokaNumber: "8.5", shlokaText: "anta-kāle cha mām eva" },
  { shlokaNumber: "8.6", shlokaText: "yaṁ yaṁ vāpi smaran bhāvaṁ" },
  { shlokaNumber: "8.7", shlokaText: "tasmāt sarveṣu kāleṣu" },
  { shlokaNumber: "8.15", shlokaText: "mām upetya punar janma" },
  { shlokaNumber: "8.16", shlokaText: "ā-brahma-bhuvanāl lokāḥ" },
  { shlokaNumber: "9.10", shlokaText: "mayādhyakṣeṇa prakṛtiḥ" },
  { shlokaNumber: "9.11", shlokaText: "avajānanti māṁ mūḍhā" },
  { shlokaNumber: "9.16", shlokaText: "ahaṁ kratur ahaṁ yajñaḥ" },
  { shlokaNumber: "9.17", shlokaText: "pitāham asya jagato" },
  { shlokaNumber: "9.18", shlokaText: "gatir bhartā prabhuḥ sākṣī" },
  { shlokaNumber: "9.19", shlokaText: "tapāmy aham ahaṁ varṣaṁ" },
  { shlokaNumber: "9.22", shlokaText: "ananyāś cintayanto māṁ" },
  { shlokaNumber: "9.23", shlokaText: "ye ’py anya-devatā-bhaktā" },
  { shlokaNumber: "9.25", shlokaText: "yānti deva-vratā devān" },
  { shlokaNumber: "9.26", shlokaText: "patram pushpam phalam toyam" },
  { shlokaNumber: "9.27", shlokaText: "yat karoṣi yad aśnāsi" },
  { shlokaNumber: "9.28", shlokaText: "śubhāśubha-phalair evaṁ" },
  { shlokaNumber: "9.29", shlokaText: "samo ’haṁ sarva-bhūteṣu" },
  { shlokaNumber: "9.30", shlokaText: "api cet su-durācāro" },
  { shlokaNumber: "9.31", shlokaText: "kṣipraṁ bhavati dharmātmā" },
  { shlokaNumber: "9.32", shlokaText: "māṁ hi pārtha vyapāśritya" },
  { shlokaNumber: "9.33", shlokaText: "kiṁ punar brāhmaṇāḥ puṇyā" },
  { shlokaNumber: "9.34", shlokaText: "man-manā bhava mad-bhakto" },
  { shlokaNumber: "10.10", shlokaText: "teṣāṁ satata-yuktānāṁ" },
  { shlokaNumber: "10.12", shlokaText: "paraṁ brahma paraṁ dhāma" },
  { shlokaNumber: "10.13", shlokaText: "āhus tvām ṛṣayaḥ sarve" },
  { shlokaNumber: "10.20", shlokaText: "aham ātmā guḍākeśa" },
  { shlokaNumber: "10.21", shlokaText: "ādityānām ahaṁ viṣṇur" },
  { shlokaNumber: "10.23", shlokaText: "rudrāṇāṁ śaṅkaraś cāsmi" },
  { shlokaNumber: "10.25", shlokaText: "maharṣīṇāṁ bhṛgur ahaṁ" },
  { shlokaNumber: "10.26", shlokaText: "aśvatthaḥ sarva-vṛkṣāṇāṁ" },
  { shlokaNumber: "10.28", shlokaText: "āyudhānām ahaṁ vajraṁ" },
  { shlokaNumber: "10.30", shlokaText: "prahlādaś cāsmi daityānāṁ" },
  { shlokaNumber: "10.31", shlokaText: "pavanaḥ pavatām asmi" },
  { shlokaNumber: "10.32", shlokaText: "sargāṇām ādir antaś ca" },
  { shlokaNumber: "10.34", shlokaText: "mṛtyuḥ sarva-haraś cāham" },
  { shlokaNumber: "10.36", shlokaText: "dyūtaṁ chalayatām asmi" },
  { shlokaNumber: "10.37", shlokaText: "vṛṣṇīnāṁ vāsudevo ’smi" },
  { shlokaNumber: "10.39", shlokaText: "yac cāpi sarva-bhūtānāṁ" },
  { shlokaNumber: "10.41", shlokaText: "yad yad vibhūtimat sattvaṁ" },
  { shlokaNumber: "11.12", shlokaText: "divi sūrya-sahasrasya" },
  { shlokaNumber: "11.33", shlokaText: "tasmāt tvam uttiṣṭha yaśo labhasva" },
  { shlokaNumber: "11.55", shlokaText: "mat-karma-kṛn mat-paramo" },
  { shlokaNumber: "12.13", shlokaText: "advesta sarva-bhutanam" },
  { shlokaNumber: "12.14", shlokaText: "santustah satatam Yogi" },
  { shlokaNumber: "13.34", shlokaText: "yathā prakāśayaty ekaḥ" },
  { shlokaNumber: "14.8", shlokaText: "tamas tv ajñāna-jaṁ viddh" },
  { shlokaNumber: "14.10", shlokaText: "rajas tamaś cābhibhūya" },
  { shlokaNumber: "15.6", shlokaText: "na tad bhāsayate sūryo" },
  { shlokaNumber: "15.14", shlokaText: "ahaṁ vaiśvānaro bhūtvā" },
  { shlokaNumber: "15.15", shlokaText: "sarvasya cāhaṁ hṛdi sanniviṣṭo" },
  { shlokaNumber: "16.1", shlokaText: "abhayaṁ sattva-saṁśuddhir" },
  { shlokaNumber: "16.2", shlokaText: "ahiṁsā satyam akrodhas" },
  { shlokaNumber: "16.3", shlokaText: "tejaḥ kṣamā dhṛtiḥ śaucam" },
  { shlokaNumber: "16.21", shlokaText: "tri-vidhaṁ narakasyedaṁ" },
  { shlokaNumber: "17.9", shlokaText: "kaṭv-amla-lavaṇāty-uṣṇa-" },
  { shlokaNumber: "17.14", shlokaText: "deva-dvija-guru-prājña-" },
  { shlokaNumber: "17.15", shlokaText: "anudvega-karaṁ vākyaṁ" },
  { shlokaNumber: "17.20", shlokaText: "dātavyam iti yad dānaṁ" },
  { shlokaNumber: "18.48", shlokaText: "saha-jaṁ karma kaunteya" },
  { shlokaNumber: "18.55", shlokaText: "bhaktyā mām abhijānāti" },
  { shlokaNumber: "18.61", shlokaText: "īśvaraḥ sarva-bhūtānāṁ" },
  { shlokaNumber: "18.65", shlokaText: "man-mana bhava mad-bhakto" },
  { shlokaNumber: "18.66", shlokaText: "sarva-dharman parityajya" },
  { shlokaNumber: "18.78", shlokaText: "yatra yogeśvaraḥ kṛṣṇo" },
];
